package org.aadi.aadityacom.product.infrastructure.primary;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import org.aadi.aadityacom.product.domain.aggregate.Product;
import org.aadi.aadityacom.product.domain.vo.*;
import org.aadi.aadityacom.shared.error.domain.Assert;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.UUID;

@Getter
@Setter
@Builder
@AllArgsConstructor
public class RestProduct {

  private String brand;
  private String color;
  private String description;
  private String name;
  private double price;
  private ProductSize size;
  private RestCategory category;
  private boolean featured;
  private List<RestPicture> pictures;
  private UUID publicId;
  private int nbInStock;

  // No-arg constructor initializes collections
  public RestProduct() {
    this.pictures = new ArrayList<>();
  }

  // All-args constructor (generated by Lombok @Builder)

  public void addPictureAttachment(List<RestPicture> pictures) {
    if (pictures != null) {
      this.pictures.addAll(pictures);
    }
  }

  public static Product toDomain(RestProduct restProduct) {
    Assert.notNull("restProduct", restProduct);

    Product.ProductBuilder builder = Product.builder()
      .productBrand(new ProductBrand(restProduct.getBrand()))
      .color(new ProductColor(restProduct.getColor()))
      .description(new ProductDescription(restProduct.getDescription()))
      .name(new ProductName(restProduct.getName()))
      .price(new ProductPrice(restProduct.getPrice()))
      .size(restProduct.getSize())
      .category(restProduct.getCategory() != null ?
        RestCategory.toDomain(restProduct.getCategory()) :
        null)
      .featured(restProduct.isFeatured())
      .nbInStock(restProduct.getNbInStock());

    if (restProduct.publicId != null) {
      builder.publicId(new PublicId(restProduct.publicId));
    }

    if (!restProduct.pictures.isEmpty()) {
      builder.pictures(RestPicture.toDomain(restProduct.getPictures()));
    }

    return builder.build();
  }

  public static RestProduct fromDomain(Product product) {
    Assert.notNull("product", product);

    return RestProduct.builder()
      .brand(product.getProductBrand() != null ? product.getProductBrand().value() : null)
      .color(product.getColor() != null ? product.getColor().value() : null)
      .description(product.getDescription() != null ? product.getDescription().value() : null)
      .name(product.getName() != null ? product.getName().value() : null)
      .price(product.getPrice() != null ? product.getPrice().value() : 0.0)
      .featured(product.getFeatured())
      .category(product.getCategory() != null ?
        RestCategory.fromDomain(product.getCategory()) :
        null)
      .size(product.getSize())
      .pictures(product.getPictures() != null ?
        RestPicture.fromDomain(product.getPictures()) :
        Collections.emptyList())
      .publicId(product.getPublicId() != null ? product.getPublicId().value() : null)
      .nbInStock(product.getNbInStock())
      .build();
  }
}
